// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/protos/protos.proto

package protos;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NewNegotiationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.NewNegotiation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string productName = 1;</code>
     */
    boolean hasProductName();
    /**
     * <code>required string productName = 1;</code>
     */
    java.lang.String getProductName();
    /**
     * <code>required string productName = 1;</code>
     */
    com.google.protobuf.ByteString
        getProductNameBytes();

    /**
     * <code>required string producerName = 2;</code>
     */
    boolean hasProducerName();
    /**
     * <code>required string producerName = 2;</code>
     */
    java.lang.String getProducerName();
    /**
     * <code>required string producerName = 2;</code>
     */
    com.google.protobuf.ByteString
        getProducerNameBytes();

    /**
     * <code>required int64 minimumAmount = 3;</code>
     */
    boolean hasMinimumAmount();
    /**
     * <code>required int64 minimumAmount = 3;</code>
     */
    long getMinimumAmount();

    /**
     * <code>required int64 maximumAmount = 4;</code>
     */
    boolean hasMaximumAmount();
    /**
     * <code>required int64 maximumAmount = 4;</code>
     */
    long getMaximumAmount();

    /**
     * <code>required int64 minimumUnitaryPrice = 5;</code>
     */
    boolean hasMinimumUnitaryPrice();
    /**
     * <code>required int64 minimumUnitaryPrice = 5;</code>
     */
    long getMinimumUnitaryPrice();

    /**
     * <code>required int64 negotiationPeriod = 6;</code>
     */
    boolean hasNegotiationPeriod();
    /**
     * <code>required int64 negotiationPeriod = 6;</code>
     */
    long getNegotiationPeriod();
  }
  /**
   * Protobuf type {@code protos.NewNegotiation}
   */
  public  static final class NewNegotiation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.NewNegotiation)
      NewNegotiationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NewNegotiation.newBuilder() to construct.
    private NewNegotiation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NewNegotiation() {
      productName_ = "";
      producerName_ = "";
      minimumAmount_ = 0L;
      maximumAmount_ = 0L;
      minimumUnitaryPrice_ = 0L;
      negotiationPeriod_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NewNegotiation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              productName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              producerName_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              minimumAmount_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              maximumAmount_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              minimumUnitaryPrice_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              negotiationPeriod_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Protos.internal_static_protos_NewNegotiation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Protos.internal_static_protos_NewNegotiation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.Protos.NewNegotiation.class, protos.Protos.NewNegotiation.Builder.class);
    }

    private int bitField0_;
    public static final int PRODUCTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object productName_;
    /**
     * <code>required string productName = 1;</code>
     */
    public boolean hasProductName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string productName = 1;</code>
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          productName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string productName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object producerName_;
    /**
     * <code>required string producerName = 2;</code>
     */
    public boolean hasProducerName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string producerName = 2;</code>
     */
    public java.lang.String getProducerName() {
      java.lang.Object ref = producerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          producerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string producerName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProducerNameBytes() {
      java.lang.Object ref = producerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        producerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MINIMUMAMOUNT_FIELD_NUMBER = 3;
    private long minimumAmount_;
    /**
     * <code>required int64 minimumAmount = 3;</code>
     */
    public boolean hasMinimumAmount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 minimumAmount = 3;</code>
     */
    public long getMinimumAmount() {
      return minimumAmount_;
    }

    public static final int MAXIMUMAMOUNT_FIELD_NUMBER = 4;
    private long maximumAmount_;
    /**
     * <code>required int64 maximumAmount = 4;</code>
     */
    public boolean hasMaximumAmount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 maximumAmount = 4;</code>
     */
    public long getMaximumAmount() {
      return maximumAmount_;
    }

    public static final int MINIMUMUNITARYPRICE_FIELD_NUMBER = 5;
    private long minimumUnitaryPrice_;
    /**
     * <code>required int64 minimumUnitaryPrice = 5;</code>
     */
    public boolean hasMinimumUnitaryPrice() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 minimumUnitaryPrice = 5;</code>
     */
    public long getMinimumUnitaryPrice() {
      return minimumUnitaryPrice_;
    }

    public static final int NEGOTIATIONPERIOD_FIELD_NUMBER = 6;
    private long negotiationPeriod_;
    /**
     * <code>required int64 negotiationPeriod = 6;</code>
     */
    public boolean hasNegotiationPeriod() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 negotiationPeriod = 6;</code>
     */
    public long getNegotiationPeriod() {
      return negotiationPeriod_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProductName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProducerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinimumAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaximumAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinimumUnitaryPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNegotiationPeriod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, productName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, producerName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, minimumAmount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, maximumAmount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, minimumUnitaryPrice_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, negotiationPeriod_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, productName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, producerName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, minimumAmount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, maximumAmount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, minimumUnitaryPrice_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, negotiationPeriod_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.Protos.NewNegotiation)) {
        return super.equals(obj);
      }
      protos.Protos.NewNegotiation other = (protos.Protos.NewNegotiation) obj;

      boolean result = true;
      result = result && (hasProductName() == other.hasProductName());
      if (hasProductName()) {
        result = result && getProductName()
            .equals(other.getProductName());
      }
      result = result && (hasProducerName() == other.hasProducerName());
      if (hasProducerName()) {
        result = result && getProducerName()
            .equals(other.getProducerName());
      }
      result = result && (hasMinimumAmount() == other.hasMinimumAmount());
      if (hasMinimumAmount()) {
        result = result && (getMinimumAmount()
            == other.getMinimumAmount());
      }
      result = result && (hasMaximumAmount() == other.hasMaximumAmount());
      if (hasMaximumAmount()) {
        result = result && (getMaximumAmount()
            == other.getMaximumAmount());
      }
      result = result && (hasMinimumUnitaryPrice() == other.hasMinimumUnitaryPrice());
      if (hasMinimumUnitaryPrice()) {
        result = result && (getMinimumUnitaryPrice()
            == other.getMinimumUnitaryPrice());
      }
      result = result && (hasNegotiationPeriod() == other.hasNegotiationPeriod());
      if (hasNegotiationPeriod()) {
        result = result && (getNegotiationPeriod()
            == other.getNegotiationPeriod());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProductName()) {
        hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getProductName().hashCode();
      }
      if (hasProducerName()) {
        hash = (37 * hash) + PRODUCERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getProducerName().hashCode();
      }
      if (hasMinimumAmount()) {
        hash = (37 * hash) + MINIMUMAMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMinimumAmount());
      }
      if (hasMaximumAmount()) {
        hash = (37 * hash) + MAXIMUMAMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMaximumAmount());
      }
      if (hasMinimumUnitaryPrice()) {
        hash = (37 * hash) + MINIMUMUNITARYPRICE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMinimumUnitaryPrice());
      }
      if (hasNegotiationPeriod()) {
        hash = (37 * hash) + NEGOTIATIONPERIOD_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNegotiationPeriod());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.Protos.NewNegotiation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Protos.NewNegotiation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Protos.NewNegotiation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Protos.NewNegotiation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Protos.NewNegotiation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Protos.NewNegotiation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Protos.NewNegotiation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Protos.NewNegotiation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Protos.NewNegotiation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.Protos.NewNegotiation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Protos.NewNegotiation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Protos.NewNegotiation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.Protos.NewNegotiation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.NewNegotiation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.NewNegotiation)
        protos.Protos.NewNegotiationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.Protos.internal_static_protos_NewNegotiation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.Protos.internal_static_protos_NewNegotiation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.Protos.NewNegotiation.class, protos.Protos.NewNegotiation.Builder.class);
      }

      // Construct using protos.Protos.NewNegotiation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        productName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        producerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        minimumAmount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        maximumAmount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        minimumUnitaryPrice_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        negotiationPeriod_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.Protos.internal_static_protos_NewNegotiation_descriptor;
      }

      @java.lang.Override
      public protos.Protos.NewNegotiation getDefaultInstanceForType() {
        return protos.Protos.NewNegotiation.getDefaultInstance();
      }

      @java.lang.Override
      public protos.Protos.NewNegotiation build() {
        protos.Protos.NewNegotiation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.Protos.NewNegotiation buildPartial() {
        protos.Protos.NewNegotiation result = new protos.Protos.NewNegotiation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.productName_ = productName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.producerName_ = producerName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.minimumAmount_ = minimumAmount_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.maximumAmount_ = maximumAmount_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.minimumUnitaryPrice_ = minimumUnitaryPrice_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.negotiationPeriod_ = negotiationPeriod_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.Protos.NewNegotiation) {
          return mergeFrom((protos.Protos.NewNegotiation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.Protos.NewNegotiation other) {
        if (other == protos.Protos.NewNegotiation.getDefaultInstance()) return this;
        if (other.hasProductName()) {
          bitField0_ |= 0x00000001;
          productName_ = other.productName_;
          onChanged();
        }
        if (other.hasProducerName()) {
          bitField0_ |= 0x00000002;
          producerName_ = other.producerName_;
          onChanged();
        }
        if (other.hasMinimumAmount()) {
          setMinimumAmount(other.getMinimumAmount());
        }
        if (other.hasMaximumAmount()) {
          setMaximumAmount(other.getMaximumAmount());
        }
        if (other.hasMinimumUnitaryPrice()) {
          setMinimumUnitaryPrice(other.getMinimumUnitaryPrice());
        }
        if (other.hasNegotiationPeriod()) {
          setNegotiationPeriod(other.getNegotiationPeriod());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasProductName()) {
          return false;
        }
        if (!hasProducerName()) {
          return false;
        }
        if (!hasMinimumAmount()) {
          return false;
        }
        if (!hasMaximumAmount()) {
          return false;
        }
        if (!hasMinimumUnitaryPrice()) {
          return false;
        }
        if (!hasNegotiationPeriod()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.Protos.NewNegotiation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.Protos.NewNegotiation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object productName_ = "";
      /**
       * <code>required string productName = 1;</code>
       */
      public boolean hasProductName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string productName = 1;</code>
       */
      public java.lang.String getProductName() {
        java.lang.Object ref = productName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            productName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string productName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProductNameBytes() {
        java.lang.Object ref = productName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string productName = 1;</code>
       */
      public Builder setProductName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        productName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string productName = 1;</code>
       */
      public Builder clearProductName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        productName_ = getDefaultInstance().getProductName();
        onChanged();
        return this;
      }
      /**
       * <code>required string productName = 1;</code>
       */
      public Builder setProductNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        productName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object producerName_ = "";
      /**
       * <code>required string producerName = 2;</code>
       */
      public boolean hasProducerName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string producerName = 2;</code>
       */
      public java.lang.String getProducerName() {
        java.lang.Object ref = producerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            producerName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string producerName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProducerNameBytes() {
        java.lang.Object ref = producerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          producerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string producerName = 2;</code>
       */
      public Builder setProducerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        producerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string producerName = 2;</code>
       */
      public Builder clearProducerName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        producerName_ = getDefaultInstance().getProducerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string producerName = 2;</code>
       */
      public Builder setProducerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        producerName_ = value;
        onChanged();
        return this;
      }

      private long minimumAmount_ ;
      /**
       * <code>required int64 minimumAmount = 3;</code>
       */
      public boolean hasMinimumAmount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 minimumAmount = 3;</code>
       */
      public long getMinimumAmount() {
        return minimumAmount_;
      }
      /**
       * <code>required int64 minimumAmount = 3;</code>
       */
      public Builder setMinimumAmount(long value) {
        bitField0_ |= 0x00000004;
        minimumAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 minimumAmount = 3;</code>
       */
      public Builder clearMinimumAmount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        minimumAmount_ = 0L;
        onChanged();
        return this;
      }

      private long maximumAmount_ ;
      /**
       * <code>required int64 maximumAmount = 4;</code>
       */
      public boolean hasMaximumAmount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 maximumAmount = 4;</code>
       */
      public long getMaximumAmount() {
        return maximumAmount_;
      }
      /**
       * <code>required int64 maximumAmount = 4;</code>
       */
      public Builder setMaximumAmount(long value) {
        bitField0_ |= 0x00000008;
        maximumAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 maximumAmount = 4;</code>
       */
      public Builder clearMaximumAmount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maximumAmount_ = 0L;
        onChanged();
        return this;
      }

      private long minimumUnitaryPrice_ ;
      /**
       * <code>required int64 minimumUnitaryPrice = 5;</code>
       */
      public boolean hasMinimumUnitaryPrice() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 minimumUnitaryPrice = 5;</code>
       */
      public long getMinimumUnitaryPrice() {
        return minimumUnitaryPrice_;
      }
      /**
       * <code>required int64 minimumUnitaryPrice = 5;</code>
       */
      public Builder setMinimumUnitaryPrice(long value) {
        bitField0_ |= 0x00000010;
        minimumUnitaryPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 minimumUnitaryPrice = 5;</code>
       */
      public Builder clearMinimumUnitaryPrice() {
        bitField0_ = (bitField0_ & ~0x00000010);
        minimumUnitaryPrice_ = 0L;
        onChanged();
        return this;
      }

      private long negotiationPeriod_ ;
      /**
       * <code>required int64 negotiationPeriod = 6;</code>
       */
      public boolean hasNegotiationPeriod() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 negotiationPeriod = 6;</code>
       */
      public long getNegotiationPeriod() {
        return negotiationPeriod_;
      }
      /**
       * <code>required int64 negotiationPeriod = 6;</code>
       */
      public Builder setNegotiationPeriod(long value) {
        bitField0_ |= 0x00000020;
        negotiationPeriod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 negotiationPeriod = 6;</code>
       */
      public Builder clearNegotiationPeriod() {
        bitField0_ = (bitField0_ & ~0x00000020);
        negotiationPeriod_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.NewNegotiation)
    }

    // @@protoc_insertion_point(class_scope:protos.NewNegotiation)
    private static final protos.Protos.NewNegotiation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.Protos.NewNegotiation();
    }

    public static protos.Protos.NewNegotiation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NewNegotiation>
        PARSER = new com.google.protobuf.AbstractParser<NewNegotiation>() {
      @java.lang.Override
      public NewNegotiation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewNegotiation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NewNegotiation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NewNegotiation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.Protos.NewNegotiation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NegotiationOverOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.NegotiationOver)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string productName = 1;</code>
     */
    boolean hasProductName();
    /**
     * <code>required string productName = 1;</code>
     */
    java.lang.String getProductName();
    /**
     * <code>required string productName = 1;</code>
     */
    com.google.protobuf.ByteString
        getProductNameBytes();

    /**
     * <code>required string producerName = 2;</code>
     */
    boolean hasProducerName();
    /**
     * <code>required string producerName = 2;</code>
     */
    java.lang.String getProducerName();
    /**
     * <code>required string producerName = 2;</code>
     */
    com.google.protobuf.ByteString
        getProducerNameBytes();
  }
  /**
   * Protobuf type {@code protos.NegotiationOver}
   */
  public  static final class NegotiationOver extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.NegotiationOver)
      NegotiationOverOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NegotiationOver.newBuilder() to construct.
    private NegotiationOver(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NegotiationOver() {
      productName_ = "";
      producerName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NegotiationOver(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              productName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              producerName_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Protos.internal_static_protos_NegotiationOver_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Protos.internal_static_protos_NegotiationOver_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.Protos.NegotiationOver.class, protos.Protos.NegotiationOver.Builder.class);
    }

    private int bitField0_;
    public static final int PRODUCTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object productName_;
    /**
     * <code>required string productName = 1;</code>
     */
    public boolean hasProductName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string productName = 1;</code>
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          productName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string productName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object producerName_;
    /**
     * <code>required string producerName = 2;</code>
     */
    public boolean hasProducerName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string producerName = 2;</code>
     */
    public java.lang.String getProducerName() {
      java.lang.Object ref = producerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          producerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string producerName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProducerNameBytes() {
      java.lang.Object ref = producerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        producerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProductName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProducerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, productName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, producerName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, productName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, producerName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.Protos.NegotiationOver)) {
        return super.equals(obj);
      }
      protos.Protos.NegotiationOver other = (protos.Protos.NegotiationOver) obj;

      boolean result = true;
      result = result && (hasProductName() == other.hasProductName());
      if (hasProductName()) {
        result = result && getProductName()
            .equals(other.getProductName());
      }
      result = result && (hasProducerName() == other.hasProducerName());
      if (hasProducerName()) {
        result = result && getProducerName()
            .equals(other.getProducerName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProductName()) {
        hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getProductName().hashCode();
      }
      if (hasProducerName()) {
        hash = (37 * hash) + PRODUCERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getProducerName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.Protos.NegotiationOver parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Protos.NegotiationOver parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Protos.NegotiationOver parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Protos.NegotiationOver parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Protos.NegotiationOver parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Protos.NegotiationOver parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Protos.NegotiationOver parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Protos.NegotiationOver parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Protos.NegotiationOver parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.Protos.NegotiationOver parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Protos.NegotiationOver parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Protos.NegotiationOver parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.Protos.NegotiationOver prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.NegotiationOver}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.NegotiationOver)
        protos.Protos.NegotiationOverOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.Protos.internal_static_protos_NegotiationOver_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.Protos.internal_static_protos_NegotiationOver_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.Protos.NegotiationOver.class, protos.Protos.NegotiationOver.Builder.class);
      }

      // Construct using protos.Protos.NegotiationOver.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        productName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        producerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.Protos.internal_static_protos_NegotiationOver_descriptor;
      }

      @java.lang.Override
      public protos.Protos.NegotiationOver getDefaultInstanceForType() {
        return protos.Protos.NegotiationOver.getDefaultInstance();
      }

      @java.lang.Override
      public protos.Protos.NegotiationOver build() {
        protos.Protos.NegotiationOver result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.Protos.NegotiationOver buildPartial() {
        protos.Protos.NegotiationOver result = new protos.Protos.NegotiationOver(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.productName_ = productName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.producerName_ = producerName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.Protos.NegotiationOver) {
          return mergeFrom((protos.Protos.NegotiationOver)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.Protos.NegotiationOver other) {
        if (other == protos.Protos.NegotiationOver.getDefaultInstance()) return this;
        if (other.hasProductName()) {
          bitField0_ |= 0x00000001;
          productName_ = other.productName_;
          onChanged();
        }
        if (other.hasProducerName()) {
          bitField0_ |= 0x00000002;
          producerName_ = other.producerName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasProductName()) {
          return false;
        }
        if (!hasProducerName()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.Protos.NegotiationOver parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.Protos.NegotiationOver) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object productName_ = "";
      /**
       * <code>required string productName = 1;</code>
       */
      public boolean hasProductName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string productName = 1;</code>
       */
      public java.lang.String getProductName() {
        java.lang.Object ref = productName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            productName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string productName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProductNameBytes() {
        java.lang.Object ref = productName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string productName = 1;</code>
       */
      public Builder setProductName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        productName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string productName = 1;</code>
       */
      public Builder clearProductName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        productName_ = getDefaultInstance().getProductName();
        onChanged();
        return this;
      }
      /**
       * <code>required string productName = 1;</code>
       */
      public Builder setProductNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        productName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object producerName_ = "";
      /**
       * <code>required string producerName = 2;</code>
       */
      public boolean hasProducerName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string producerName = 2;</code>
       */
      public java.lang.String getProducerName() {
        java.lang.Object ref = producerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            producerName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string producerName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProducerNameBytes() {
        java.lang.Object ref = producerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          producerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string producerName = 2;</code>
       */
      public Builder setProducerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        producerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string producerName = 2;</code>
       */
      public Builder clearProducerName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        producerName_ = getDefaultInstance().getProducerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string producerName = 2;</code>
       */
      public Builder setProducerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        producerName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.NegotiationOver)
    }

    // @@protoc_insertion_point(class_scope:protos.NegotiationOver)
    private static final protos.Protos.NegotiationOver DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.Protos.NegotiationOver();
    }

    public static protos.Protos.NegotiationOver getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NegotiationOver>
        PARSER = new com.google.protobuf.AbstractParser<NegotiationOver>() {
      @java.lang.Override
      public NegotiationOver parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NegotiationOver(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NegotiationOver> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NegotiationOver> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.Protos.NegotiationOver getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetProducerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.GetProducerInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string producerName = 1;</code>
     */
    boolean hasProducerName();
    /**
     * <code>required string producerName = 1;</code>
     */
    java.lang.String getProducerName();
    /**
     * <code>required string producerName = 1;</code>
     */
    com.google.protobuf.ByteString
        getProducerNameBytes();
  }
  /**
   * Protobuf type {@code protos.GetProducerInfo}
   */
  public  static final class GetProducerInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.GetProducerInfo)
      GetProducerInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetProducerInfo.newBuilder() to construct.
    private GetProducerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetProducerInfo() {
      producerName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetProducerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              producerName_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Protos.internal_static_protos_GetProducerInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Protos.internal_static_protos_GetProducerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.Protos.GetProducerInfo.class, protos.Protos.GetProducerInfo.Builder.class);
    }

    private int bitField0_;
    public static final int PRODUCERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object producerName_;
    /**
     * <code>required string producerName = 1;</code>
     */
    public boolean hasProducerName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string producerName = 1;</code>
     */
    public java.lang.String getProducerName() {
      java.lang.Object ref = producerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          producerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string producerName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProducerNameBytes() {
      java.lang.Object ref = producerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        producerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProducerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, producerName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, producerName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.Protos.GetProducerInfo)) {
        return super.equals(obj);
      }
      protos.Protos.GetProducerInfo other = (protos.Protos.GetProducerInfo) obj;

      boolean result = true;
      result = result && (hasProducerName() == other.hasProducerName());
      if (hasProducerName()) {
        result = result && getProducerName()
            .equals(other.getProducerName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProducerName()) {
        hash = (37 * hash) + PRODUCERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getProducerName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.Protos.GetProducerInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Protos.GetProducerInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Protos.GetProducerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Protos.GetProducerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Protos.GetProducerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Protos.GetProducerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Protos.GetProducerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Protos.GetProducerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Protos.GetProducerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.Protos.GetProducerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Protos.GetProducerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Protos.GetProducerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.Protos.GetProducerInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.GetProducerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.GetProducerInfo)
        protos.Protos.GetProducerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.Protos.internal_static_protos_GetProducerInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.Protos.internal_static_protos_GetProducerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.Protos.GetProducerInfo.class, protos.Protos.GetProducerInfo.Builder.class);
      }

      // Construct using protos.Protos.GetProducerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        producerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.Protos.internal_static_protos_GetProducerInfo_descriptor;
      }

      @java.lang.Override
      public protos.Protos.GetProducerInfo getDefaultInstanceForType() {
        return protos.Protos.GetProducerInfo.getDefaultInstance();
      }

      @java.lang.Override
      public protos.Protos.GetProducerInfo build() {
        protos.Protos.GetProducerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.Protos.GetProducerInfo buildPartial() {
        protos.Protos.GetProducerInfo result = new protos.Protos.GetProducerInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.producerName_ = producerName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.Protos.GetProducerInfo) {
          return mergeFrom((protos.Protos.GetProducerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.Protos.GetProducerInfo other) {
        if (other == protos.Protos.GetProducerInfo.getDefaultInstance()) return this;
        if (other.hasProducerName()) {
          bitField0_ |= 0x00000001;
          producerName_ = other.producerName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasProducerName()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.Protos.GetProducerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.Protos.GetProducerInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object producerName_ = "";
      /**
       * <code>required string producerName = 1;</code>
       */
      public boolean hasProducerName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string producerName = 1;</code>
       */
      public java.lang.String getProducerName() {
        java.lang.Object ref = producerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            producerName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string producerName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProducerNameBytes() {
        java.lang.Object ref = producerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          producerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string producerName = 1;</code>
       */
      public Builder setProducerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        producerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string producerName = 1;</code>
       */
      public Builder clearProducerName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        producerName_ = getDefaultInstance().getProducerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string producerName = 1;</code>
       */
      public Builder setProducerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        producerName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protos.GetProducerInfo)
    }

    // @@protoc_insertion_point(class_scope:protos.GetProducerInfo)
    private static final protos.Protos.GetProducerInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.Protos.GetProducerInfo();
    }

    public static protos.Protos.GetProducerInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetProducerInfo>
        PARSER = new com.google.protobuf.AbstractParser<GetProducerInfo>() {
      @java.lang.Override
      public GetProducerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetProducerInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetProducerInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetProducerInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.Protos.GetProducerInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_NewNegotiation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_NewNegotiation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_NegotiationOver_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_NegotiationOver_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_GetProducerInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_GetProducerInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/java/protos/protos.proto\022\006pro" +
      "tos\"\241\001\n\016NewNegotiation\022\023\n\013productName\030\001 " +
      "\002(\t\022\024\n\014producerName\030\002 \002(\t\022\025\n\rminimumAmou" +
      "nt\030\003 \002(\003\022\025\n\rmaximumAmount\030\004 \002(\003\022\033\n\023minim" +
      "umUnitaryPrice\030\005 \002(\003\022\031\n\021negotiationPerio" +
      "d\030\006 \002(\003\"<\n\017NegotiationOver\022\023\n\013productNam" +
      "e\030\001 \002(\t\022\024\n\014producerName\030\002 \002(\t\"\'\n\017GetProd" +
      "ucerInfo\022\024\n\014producerName\030\001 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protos_NewNegotiation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_NewNegotiation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_NewNegotiation_descriptor,
        new java.lang.String[] { "ProductName", "ProducerName", "MinimumAmount", "MaximumAmount", "MinimumUnitaryPrice", "NegotiationPeriod", });
    internal_static_protos_NegotiationOver_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_NegotiationOver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_NegotiationOver_descriptor,
        new java.lang.String[] { "ProductName", "ProducerName", });
    internal_static_protos_GetProducerInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_GetProducerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_GetProducerInfo_descriptor,
        new java.lang.String[] { "ProducerName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
