%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.11.0

-ifndef(protos).
-define(protos, true).

-define(protos_gpb_version, "4.11.0").

-ifndef('AUTHENTICATION_PB_H').
-define('AUTHENTICATION_PB_H', true).
-record('Authentication',
        {type                   :: 'REGISTER' | 'LOGIN' | integer(), % = 1, enum Authentication.AuthType
         userType               :: 'PRODUCER' | 'IMPORTER' | integer(), % = 2, enum Authentication.UserType
         username               :: iodata(),        % = 3
         password               :: iodata()         % = 4
        }).
-endif.

-ifndef('SERVERRESPONSE_PB_H').
-define('SERVERRESPONSE_PB_H', true).
-record('ServerResponse',
        {success                :: boolean() | 0 | 1 % = 1
        }).
-endif.

-ifndef('PRODUCE_PB_H').
-define('PRODUCE_PB_H', true).
-record('Produce',
        {productName            :: iodata(),        % = 1
         minimumAmount          :: integer(),       % = 2, 32 bits
         maximumAmount          :: integer(),       % = 3, 32 bits
         minimumUnitaryPrice    :: integer(),       % = 4, 32 bits
         negotiationPeriod      :: integer()        % = 5, 32 bits
        }).
-endif.

-ifndef('IMPORT_PB_H').
-define('IMPORT_PB_H', true).
-record('Import',
        {productName            :: iodata(),        % = 1
         producerName           :: iodata(),        % = 2
         quantity               :: integer(),       % = 3, 32 bits
         unitaryPrice           :: integer()        % = 4, 32 bits
        }).
-endif.

-ifndef('SUBSCRIBEPRODUCER_PB_H').
-define('SUBSCRIBEPRODUCER_PB_H', true).
-record('SubscribeProducer',
        {username               :: iodata(),        % = 1
         producerName           :: iodata()         % = 2
        }).
-endif.

-ifndef('UNSUBSCRIBEPRODUCER_PB_H').
-define('UNSUBSCRIBEPRODUCER_PB_H', true).
-record('UnsubscribeProducer',
        {username               :: iodata(),        % = 1
         producerName           :: iodata()         % = 2
        }).
-endif.

-ifndef('SALEINFO_PB_H').
-define('SALEINFO_PB_H', true).
-record('SaleInfo',
        {username               :: iodata(),        % = 1
         quantity               :: integer(),       % = 2, 32 bits
         price                  :: integer()        % = 3, 32 bits
        }).
-endif.

-ifndef('DEALERTIMEOUT_PB_H').
-define('DEALERTIMEOUT_PB_H', true).
-record('DealerTimeout',
        {success                :: boolean() | 0 | 1, % = 1
         producerName           :: iodata(),        % = 2
         productName            :: iodata(),        % = 3
         sales = []             :: [protos:'SaleInfo'()] | undefined % = 4
        }).
-endif.

-ifndef('RESPONSEIMPORT_PB_H').
-define('RESPONSEIMPORT_PB_H', true).
-record('ResponseImport',
        {producerName           :: iodata(),        % = 1
         sale                   :: protos:'SaleInfo'() % = 2
        }).
-endif.

-endif.
